committed by script

diff --git a/Dev b/Dev
--- a/Dev
+++ b/Dev
@@ -704,24 +704,37 @@ function DownloadVsCodeExtensions()
 
         Info "Downloading C# VS Code extension ... "
 
-        sudo rm -rf /Temp/Extensions/CSharp.vsix
+        sudo rm -rf /Temp/Extensions/CSharp.vsix /Temp/Extensions/DotNetInstallTool.vsix
         sudo chmod -R 777 --preserve-root /Temp/Extensions
         sudo mkdir -p /Temp/Extensions
         find /Temp -maxdepth 1 -name "*vspackage?target*" | xargs rm -rf
         ua="Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:15.0) Gecko/20100101 Firefox/15.0.1"
-        latestVersion=$(curl -s https://api.github.com/repos/dotnet/vscode-csharp/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')
-        latestVersion="${latestVersion#v}"
-        Info "Version: $latestVersion"
-        if [[ "$latestVersion" == "" ]]; then
-            Error "C# VS Code extension's latest version could not be found"
-            return
+        latestCSharpVersion=$(curl -s https://api.github.com/repos/dotnet/vscode-csharp/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')
+        latestCSharpVersion="${latestCSharpVersion#v}"
+        echo "C# Extension Version: $latestCSharpVersion"
+        if [[ "$latestCSharpVersion" == "" ]]; then
+            echo "Error: C# VS Code extension's latest version could not be found."
+            exit 1
         fi
         sudo wget --save-cookies cookies.txt --keep-session-cookies https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp
-        sudo wget -U "$ua" --load-cookies cookies.txt https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-dotnettools/vsextensions/csharp/$latestVersion/vspackage?targetPlatform=linux-x64
+        sudo wget -U "$ua" --load-cookies cookies.txt https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-dotnettools/vsextensions/csharp/$latestCSharpVersion/vspackage?targetPlatform=linux-x64
         sudo mv vspackage\?targetPlatform\=linux-x64 CSharp.gz
         sudo gunzip -v CSharp.gz
         sudo mv CSharp CSharp.vsix
         sudo mv CSharp.vsix /Temp/Extensions/
+        latestDotNetToolVersion=$(curl -s https://api.github.com/repos/dotnet/vscode-dotnet-runtime/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')
+        latestDotNetToolVersion="${latestDotNetToolVersion#v}"
+        echo ".NET Install Tool Extension Version: $latestDotNetToolVersion"
+        if [[ "$latestDotNetToolVersion" == "" ]]; then
+            echo "Error: .NET Install Tool VS Code extension's latest version could not be found."
+            exit 1
+        fi
+        sudo wget --save-cookies cookies.txt --keep-session-cookies https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.vscode-dotnet-runtime
+        sudo wget -U "$ua" --load-cookies cookies.txt https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-dotnettools/vsextensions/vscode-dotnet-runtime/$latestDotNetToolVersion/vspackage?targetPlatform=linux-x64
+        sudo mv vspackage\?targetPlatform\=linux-x64 DotNetInstallTool.gz
+        sudo gunzip -v DotNetInstallTool.gz
+        sudo mv DotNetInstallTool DotNetInstallTool.vsix
+        sudo mv DotNetInstallTool.vsix /Temp/Extensions/
         sudo chmod -R 777 --preserve-root /Temp/Extensions
 
         Success "Downloaded C# VS Code extension "
